#!/usr/bin/env python3
"""Generate a random-opening EPD suite for match variance reduction
(plan §27: evaluation-only, applied symmetrically to both engines).

Each opening is `plies` uniformly random legal moves from the start
position, generated by driving Stockfish's `go perft 1` move listing
with a fixed seed. Openings that end in terminal positions are skipped.
"""
import random
import subprocess
import sys

SF = "/usr/games/stockfish"
COUNT = int(sys.argv[1]) if len(sys.argv) > 1 else 250
PLIES = int(sys.argv[2]) if len(sys.argv) > 2 else 4
SEED = int(sys.argv[3]) if len(sys.argv) > 3 else 20260814
OUT = sys.argv[4] if len(sys.argv) > 4 else "tools/openings_4ply.epd"

rng = random.Random(SEED)
proc = subprocess.Popen(
    [SF], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True, bufsize=1
)

def send(cmd):
    proc.stdin.write(cmd + "\n")

def legal_moves(moves):
    send(f"position startpos moves {' '.join(moves)}")
    send("go perft 1")
    legal = []
    while True:
        line = proc.stdout.readline()
        if line.startswith("Nodes searched"):
            break
        if ":" in line and len(line.split(":")[0].strip()) in (4, 5):
            legal.append(line.split(":")[0].strip())
    return legal

def fen(moves):
    send(f"position startpos moves {' '.join(moves)}")
    send("d")
    result = None
    while True:
        line = proc.stdout.readline()
        if line.startswith("Fen:"):
            result = line.split("Fen:")[1].strip()
        if line.startswith("Checkers:"):
            return result

send("uci")
while not proc.stdout.readline().startswith("uciok"):
    pass

seen = set()
openings = []
while len(openings) < COUNT:
    moves = []
    ok = True
    for _ in range(PLIES):
        legal = legal_moves(moves)
        if not legal:
            ok = False
            break
        moves.append(rng.choice(sorted(legal)))
    if not ok:
        continue
    position_fen = fen(moves)
    if position_fen in seen:
        continue
    seen.add(position_fen)
    openings.append(position_fen)

send("quit")
with open(OUT, "w") as f:
    for position_fen in openings:
        f.write(position_fen + "\n")
print(f"wrote {len(openings)} openings to {OUT}")
